name: Run Python scripts

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Python scripts
      run: |
        python Scripts/Get-Renewed-Rules.py
        python Scripts/Merge-Rules-Renew.py
        python Scripts/Merge-Rules-ALL.py
        python Scripts/ALL-Lite-Convert.py
        python Scripts/ALL-Lite-Split.py

    - name: Upload ALL-Rule
      uses: actions/upload-artifact@v2
      with:
        name: all-rule
        path: /home/runner/work/AdGuardHomeRules/AdGuardHomeRules/all.txt

    - name: Upload ALL-Rule-Lite
      uses: actions/upload-artifact@v2
      with:
        name: all-lite
        path: /home/runner/work/AdGuardHomeRules/AdGuardHomeRules/all-lite.txt 

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Part/* Renew/* Scripts/* all.txt all-lite.txt
        git commit -m "Update rules files"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
